behaviors:
  KartAgent:
    trainer_type: sac

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 120
      buffer_size: 12000
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # SAC-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 50000
    checkpoint_interval: 50000
    threaded: true
    init_path: null

    # behavior cloning
    # behavioral_cloning:
    #  demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
    #  strength: 0.5
    #  steps: 150000
    #  batch_size: 512
    #  num_epoch: 3
    # samples_per_update: 0

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

      # curiosity module
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4

    # self-play
    self_play: null
      # window: 10
      # play_against_latest_model_ratio: 0.5
      # save_steps: 50000
      # swap_steps: 2000
      # team_change: 100000